### ISSUE TITLE
nested on_change call back seems not to work

### ISSUE THREAD

**Issue by WernerJacoby** [google/mesop#725] opened 2024-08-03 11:06 UTC
**Describe the bug**
events should trigger a call back, i.e. ClickEvent or RadioChangeEvent.
This should also work for nested events

**To Reproduce**

I started using the code of mesop/examples/testing/complex_layout.py.
I added on_change call backs for the given radio buttons, including event handlers (on_ch1, on_ch2)
Those would trigger State changes (s.radio1, s.radio2).
To check them, I added me.text items (.e.g. me.text("XX1 " + state.radio1)

These state changes would not happen, after clicking on e.g. radio button 1/2.

**Expected behavior**
After clicking on radio button 2, state.radio1 should change to the button value and be displayed.

**Desktop System Info**

- OS: macOS 14.5 (23F79)
- Browser safari
- Version 17.5

**Additional context**
Appendix:
  modified file complex_layout.py
[complex_layout.py.md](https://github.com/user-attachments/files/16479265/complex_layout.py.md)

**Comment by WernerJacoby** [comment] 2024-08-03 11:09
maybe I'm missing something?

Is there any more documentation on the placement of button call backs?

**Comment by richard-to** [comment] 2024-08-05 17:41
Can you provide a small sample code of the issue? I think that will helps us look into the issue a bit easier. Thanks.

**Comment by WernerJacoby** [comment] 2024-08-06 16:46
**small sample code**
see appendix

**Expected behavior**
clicking button 'Reverse colors' should reverse colors and increment cnt1
=> this happens as expected

clicking radio button 'Radio 2' should set state state.radio1 and increment cnt2
=> this does not happen

**Additional context**
Appendix:
  file minimal_radio.py

[minimal_radio.py.md](https://github.com/user-attachments/files/16513294/minimal_radio.py.md)

**Comment by WernerJacoby** [comment] 2024-08-06 17:16
**another comment**

the radio button callback is function on_ch1().
It would increment cnt2, which is displayed (together with cnt1) using me.text()

Since cnt2 stays at 0, on_ch1() seems not to be called.

This seems unexpected ..

**a note about file types to be appended here**

Since Mesop is a pure python framework, one should expect that python files (*.py) can be appended.
Still they will be rejected.

Might be for historical reasons ?

**Comment by richard-to** [comment] 2024-08-07 21:17
Yeah I'm not sure why Github does not let upload .py files. Usually I would just add it to a gist. Or inline the code in the comment using the code fence block.

-----

Anyway, thanks for posting the code. I took a look. Seems like the issue is you need to add different values for the radio buttons. Since you didn't specify the values, they default to empty string I think. 

Since both values are empty string, they don't detect a change since the value is technically the same.

To resolve can do something like this:

```python
      me.radio(
        options=[
          me.RadioOption(label="Radio 1", value="1"),
          me.RadioOption(label="Radio 2", value="2"),
        ],
        on_change=on_ch1,
      )
```

You'll also need to update your handler to `e.value` instead of `e.label`

**Comment by WernerJacoby** [comment] 2024-08-08 09:09
Hi Richard,
thanks for your comment.

So adding value assignment to the RadioOption call actually changed this behavior!

Why would this value assignment be mandatory to trigger the callback?
Seems not to be obvious to me (?)

Anyway, thanks for pointing this out :-)

**Comment by richard-to** [comment] 2024-08-08 16:51
The reason is that both radio boxes have the same value of empty string. So although the selected radio box has changed, the value of the radio ground has not changed.

------


Ok. Going to close this issue.

**Closed by richard-to** 2024-08-08 16:51 UTC
Labels: bug
