### ISSUE TITLE
Cannot save mesop web-app data (state sessions)  into firestore collection

### ISSUE THREAD

**Issue by sptom** [google/mesop#961] opened 2024-09-13 22:26 UTC
**Describe the bug**

Built a simple web app via mesop - a web page with a single text box, which saves the string into a state class field "state.input" - a single python file named main.py
Followed the deployment instructions with google sdk, got a link and saw that the webpage loads.
For the next step, I tried to connect the app to a firestore dataset. I edited the enviromental variables

```MESOP_STATE_SESSION_BACKEND=firestore```
```MESOP_STATE_SESSION_BACKEND_FIRESTORE_COLLECTION=submitted_content``` [the desired collection name]

Then, I uploaded the new version with the said environmental variables.
I did not configure the dataset name as it was written in the mesop documentation that it can only use the '(default)' dataset. 

For some reason, not only the integration with the dataset did not succeed, but now the app does not load. Instead, I the webpage only shows "Service Unavailable" now. 

**Expected behavior**
Find the 'input' build of 'state' class with the instances written in the webpage field in the default firestore database, under a collection named 'submitted_content'. 

**Screenshots**
![image](https://github.com/user-attachments/assets/bc52bdd2-0f4b-48a3-ba03-b057dac395a3)

**Desktop System Info**

- OS: Windows 11
- Browser chrome
- Version 128.0.6613.137

**Comment by richard-to** [comment] 2024-09-13 23:41
In the Cloud Run logs, do you see any specific error messages? I'll see if I can reproduce the error (but that will have to wait until Monday)

**Comment by sptom** [comment] 2024-09-14 22:07
Hi, thanks for the quick response!

There are indeed errors. 11 of them:
The first ten errors are a sequence of five pairs of the following errors:

**1**
```2024-09-14 01:11:12.740 IDT
GET50367 B1.9 sChrome 128 https://main-page-832462213398.us-east1.run.app/
```

```{
httpRequest: {15}
insertId: "66e4b882000c86f4dcbb675b"
labels: {1}
logName: "projects/finfluencrpdf/logs/run.googleapis.com%2Frequests"
receiveLocation: "us-east1"
receiveTimestamp: "2024-09-13T22:11:14.829298652Z"
resource: {2}
severity: "ERROR"
spanId: "b9928f23dd2cc198"
textPayload: "The request failed because either the HTTP response was malformed or connection to the instance had an error. Additional troubleshooting documentation can be found at: https://cloud.google.com/run/docs/troubleshooting#malformed-response-or-connection-error"
timestamp: "2024-09-13T22:11:12.740882Z"
trace: "projects/finfluencrpdf/traces/04d48c123043707707733d552aa7c81a"
traceSampled: true
}
```

**2**
```
2024-09-14 01:11:14.687 IDT
Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker worker.init_process() File "/layers/google.python.pip/pip/lib/python3.12/site-packages/guni
```

``` 
File "/layers/google.python.pip/pip/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/layers/google.python.pip/pip/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
```

This pair happens five times repeatedly and finally, the final error is 

```
2024-09-14 01:11:29.066 IDT
GET5000 B0 msChrome 128 https://main-page-832462213398.us-east1.run.app/favicon.ico
 ```

```
{
httpRequest: {
cacheFillBytes: "0"
cacheHit: false
cacheLookup: false
cacheValidatedWithOriginServer: false
latency: "0s"
protocol: "HTTP/1.1"
referer: "https://main-page-832462213398.us-east1.run.app/"
remoteIp: "77.137.79.180"
requestMethod: "GET"
requestSize: "1234"
requestUrl: "https://main-page-832462213398.us-east1.run.app/favicon.ico"
responseSize: "0"
serverIp: "216.239.32.53"
status: 500
userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
}
insertId: "66e4b89100010c2cd8a4b7b6"
logName: "projects/finfluencrpdf/logs/run.googleapis.com%2Frequests"
receiveLocation: "us-east1"
receiveTimestamp: "2024-09-13T22:11:29.144701285Z"
resource: {
labels: {
configuration_name: "main-page"
location: "us-east1"
project_id: "finfluencrpdf"
revision_name: "main-page-00013-vs2"
service_name: "main-page"
}
type: "cloud_run_revision"
}
severity: "ERROR"
spanId: "e931af51189a41c0"
textPayload: "The request failed because the instance could not start successfully."
timestamp: "2024-09-13T22:11:29.066687Z"
trace: "projects/finfluencrpdf/traces/eb9a0feba95bc41343039bda9dd079c3"
traceSampled: false
}
```

I'm afraid that it might have something to do with not configuring my firestore database properly. I do see and can access a database manually, which is marked as 'native' in terms of **mode**, like they suggest to set it up here:
https://cloud.google.com/firestore/docs/create-database-server-client-library#firestore_setup_dataset_pt1-python_async

![image](https://github.com/user-attachments/assets/bad23a93-6b2f-464e-9f1f-5d6a54d53ca7)

but there are several things that I might be missing like configuring 'google applicaiton credentials' as in environmental variable, and pehaps also adding a server client library to the app

![image](https://github.com/user-attachments/assets/8c31c770-58ce-4956-ab34-b527fd488f2b)

Although maybe it's not relevant as the app itself is stored on 'google cloud run' and not on 'firestore' as I understand. 

Any idea what I might be missing?

**Comment by richard-to** [comment] 2024-09-16 20:09
Hmm, your set up seems reasonable given the information you posted. You're right that if you're on Cloud Run it should use the application default credentials for the Cloud Run job. I'm trying to remember if there are any specific IAM roles for accessing Firestore that you may need to add to your Cloud Run service account. However, the error messages do not seem to be pointing to a permission error though.

But one thing you can test is running the app locally and seeing if that works with Firestore. If it does, that seems like it could be an issue with IAM roles.

**Comment by richard-to** [comment] 2024-09-18 01:43
I tested Firestore on Cloud Run just now and it worked for me.

I think I'd first test that you can access firestore when running your app locally.

If it works locally, then I'd probably check it works on Cloud Run with the default behavior.

If that works, then I'd check that the environment variables were set correctly in Cloud Run and that the Cloud Run job and Firestore db are in the same project.

**Comment by richard-to** [comment] 2024-10-15 02:04
Going to close this issue since there hasn't been any activity in a while. Feel free to reopen if this is still an issue.

**Closed by richard-to** 2024-10-15 02:04 UTC
Labels: bug
