### ISSUE TITLE
Create Build

### ISSUE THREAD

**Issue by runtimevic** [google/mesop#562] opened 2024-06-30 07:55 UTC
Hello, 
there is no documentation on how to create the build, what we need and the steps to carry out, there is nothing in the documentation or steps to follow to obtain the build for example and have the app run locally, for example...

**Comment by richard-to** [comment] 2024-06-30 15:50
What do you mean by build? Do you want to create a modified Mesop binary rather than install from pip?

**Comment by runtimevic** [comment] 2024-06-30 16:29
> What do you mean by build? Do you want to create a modified Mesop binary rather than install from pip?

How does the application created for example in local Windows run in production and make it a web page?

**Comment by pranshu-raj-211** [comment] 2024-06-30 16:35
How about using a docker container to run it, other methods (cloud run, gunicorn) are also given in the deployment docs.
The docker example is given [here](https://google.github.io/mesop/guides/deployment/#dockerfile).

**Comment by runtimevic** [comment] 2024-06-30 16:47
> How about using a docker container to run it, other methods (cloud run, gunicorn) are also given in the deployment docs. The docker example is given [here](https://google.github.io/mesop/guides/deployment/#dockerfile).

It can be Gunicorn on local windows without docker...???

**Comment by richard-to** [comment] 2024-06-30 17:07
You shouldn't need to run gunicorn for using mesop locally. 

I don't have a Windows machine, but we have some instructions here. There's a hello world example: https://google.github.io/mesop/getting_started/installing

**Comment by runtimevic** [comment] 2024-06-30 17:20
> You shouldn't need to run gunicorn for using mesop locally.
> 
> I don't have a Windows machine, but we have some instructions here. There's a hello world example: https://google.github.io/mesop/getting_started/installing

Hello, 
The link you sent is clear but I don't want to run with: mesop hello_world.py
How can I create the build with mesop, for example with Flet is it possible to create the app and run it with Gunicorn..., with mesop what would it be like?

**Comment by richard-to** [comment] 2024-06-30 17:25
Yes, you can run mesop with gunicorn without docker. 

If you have gunicorn installed on Windows, then you can probably run a command like:

```
gunicorn --bind :8080 main:me
```

Then you should be able to view the app on localhost:8080

This assumes that your Mesop app is named "main.py". 

By convention, we do `import mesop as me` so the `me` refers to the main Mesop library module which is also a callable (e.g. a function) that conforms to WSGI.

**Comment by runtimevic** [comment] 2024-06-30 17:33
> Sí, puedes ejecutar mesop con gunicorn sin docker.
> 
> Si tienes gunicorn instalado en Windows, entonces probablemente puedas ejecutar un comando como:
> 
> ```
> gunicorn --bind :8080 main:me
> ```
> 
> Entonces deberías poder ver la aplicación en localhost:8080
> 
> Esto supone que su aplicación Mesop se llama "main.py".
> 
> `import mesop as me`Por convención, lo hacemos `me`como referencia al módulo principal de la biblioteca Mesop, que también es un elemento invocable (por ejemplo, una función) que se ajusta a WSGI.

(.venv) PS D:\Mesop_Google> gunicorn --bind :8080 main:me
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Mesop_Google\.venv\Scripts\gunicorn.exe\__main__.py", line 4, in <module>
  File "D:\Mesop_Google\.venv\Lib\site-packages\gunicorn\app\wsgiapp.py", line 9, in <module>
    from gunicorn.app.base import Application
  File "D:\Mesop_Google\.venv\Lib\site-packages\gunicorn\app\base.py", line 11, in <module>
    from gunicorn import util
  File "D:\Mesop_Google\.venv\Lib\site-packages\gunicorn\util.py", line 8, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

**Comment by richard-to** [comment] 2024-06-30 17:42
I see. Apparently gunicorn does not work on Windows: https://stackoverflow.com/questions/45228395/error-no-module-named-fcntl

Is there a reason you want to run with `gunicorn` and not just `mesop main.py`? If you're not running the app in production, I think `mesop main.py` should be fine. You'd be able to view the website at localhost:32123

Looks like there's an alternative there to use something called "waitress". I haven't tried it but seems simple enough:

```
pip install waitress
waitress-serve --listen=127.0.0.1:5000 main:me
```

**Comment by richard-to** [comment] 2024-07-01 16:57
Sounds like using waitress worked? I'll close this issue now. Feel free to reopen if the issue is not resolved.

**Closed by richard-to** 2024-07-01 16:57 UTC
