### ISSUE TITLE
Component Tree Diff Edge case leading to components not being removed on update (maybe)

### ISSUE THREAD

**Issue by richard-to** [google/mesop#311] opened 2024-05-26 14:57 UTC
I haven't verified if this is a bug with the component tree diff or not yet. I'd have to figure out how to reproduce it first.

I had some code like this:

```python
# Event handler on the radio. 
me.radio(...)
if state.radio_result is True
  me.text("Success")
elif state.radio_result is False:
  me.text("Fail")
```

What happened was every time I clicked the radio button, the me.text was appended and not replaced.

But this variation worked fine:

```python
# Event handler on the radio. 
me.radio(...) 
me.text("Success" if state.radio_result else me.text("Fail"))
```

**Comment by wwwillchen** [comment] 2024-05-27 04:28
I couldn't reproduce your scenario, but I was able to reproduce another issue with component tree diffs:

```py
import mesop as me

@me.page(path="/diff_edge_case")
def app():
    me.text("diff_edge_case")
    me.radio(options=[me.RadioOption(label="1", value="1",),
                      me.RadioOption(label="2", value="2",)], on_change=on_change)
    if me.state(State).value == "1":
        me.checkbox("check me")
    else: 
        me.checkbox("i will be erroneously checked")


@me.stateclass
class State:
    value: str ="1"

def on_change(e: me.RadioChangeEvent):
    me.state(State).value = e.value
```

If I check the checkbox, and then I toggle the radio option, the checkbox (the second one) **should**  be unchecked, however because I believe the diff algorithm thinks the component instance is the same, it'll treat the second checkbox as the same instance as the first checkbox and the checkbox will be erroneously checked.

You can manually fix this error by setting different key values for each checkbox and then it behaves as expected.

I think one possible way of fixing this is by creating an implicit key which is the hash of the traceback, this way the first and second checkbox will have different keys. I'll try sending a PR for this and we can see whether it makes sense (the concern with hashing a traceback is that it could add a non-trivial runtime overhead for each component instance).

**Comment by wwwillchen** [comment] 2024-05-27 04:38
Actually the above issue is not specific to component tree diffs, it's something that's always been there - I'll open a separate issue for it (#312)

**Comment by wwwillchen** [comment] 2024-10-26 08:19
closing b/c there hasn't been a clear repro for the original issue (although I have seen this on rare occasions)

**Closed by wwwillchen** 2024-10-26 08:19 UTC
Labels: bug
