### ISSUE TITLE
Page refresh will hide functioning of radio button

### ISSUE THREAD

**Issue by WernerJacoby** [google/mesop#772] opened 2024-08-10 07:35 UTC
**Describe the bug**
I'm not sure if it is a bug or a 'feature'

**To Reproduce**
My sample code (see appendix) will refresh the page every second (exactly 10 times)
During this time, the radio button (options '1' or '2') will not react on a button click.

Only after the last yield of generator function refreshGen() the radio button will start to work.

**Expected behavior**
I would hope for a page refresh not interfering with button callback functions.

Is there any other way to get both of them ?

**Desktop System Info**

OS: macOS 14.5 (23F79)
Browser safari
Version 17.5

**Additional context**

Appendix:

[live.py.md](https://github.com/user-attachments/files/16568835/live.py.md)

**Comment by wwwillchen** [comment] 2024-08-10 22:56
I'll close this as a dupe of #623 since it's the same issue. Could you let me know what's the real-world use case you have? I can't quite tell what's the purpose from the sample code.

**Closed by wwwillchen** 2024-08-10 22:56 UTC
Labels: bug

**Comment by WernerJacoby** [comment] 2024-08-12 13:40
Hi,

the goal I would like to achieve is having a dashboard with two
graphs plotted, being controlled by radio buttons which define
the amount of history needed.

Below them I like to display an Image of a webcam,
being refreshed periodically every other second.

Should not be a very exotic use case ..

Cheers,
Werner

Will Chen ***@***.***> schrieb am So. 11. Aug. 2024 um 00:57:

**Comment by wwwillchen** [comment] 2024-08-13 06:32
You should be able to do something like this with https://google.github.io/mesop/web-components/ - feel free to open something on Discussions if you get stuck.
